[project]
name = "dummy"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi>=0.115.11",
    "jinja2>=3.1.6",
    "openai>=1.67.0",
    "pyyaml>=6.0.2",
    "tavily>=1.1.0",
]
