[project]
name = "student assistant"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "uvicorn>=0.35.0",
    "fastapi>=0.116.1",
    "openai>=1.100.2",
]

[tool.ruff]
line-length = 160
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "B", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
